[project]
name = "frontend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Hannah Zemack", email = "hannah.zemack@gmail.com" }
]
requires-python = ">=3.13"
dependencies = ["streamlit", "httpx"]

[project.scripts]
frontend = "frontend:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
