# services:
#   backend:
#     container_name: backend
#     platform: linux/amd64
#     build:
#       context: .
#       dockerfile: dockerfiles/backend.dockerfile
#     ports:
#       - "8000:8000"
#     image: ${ACR_LOGIN_SERVER}/backend:${IMAGE_TAG:-latest}

#   frontend:
#     container_name: frontend
#     platform: linux/amd64
#     build:
#       context: .
#       dockerfile: dockerfiles/frontend.dockerfile
#     ports:
#       - "8501:8501"
#     environment:
#       BACKEND_URL: http://backend:8000
#     image: ${ACR_LOGIN_SERVER}/frontend:${IMAGE_TAG:-latest}



services:
  backend:
    container_name: backend
    platform: linux/amd64
    build:
      context: .
      dockerfile: dockerfiles/backend.dockerfile
    ports: #mappar hosts till container backend 8000
      - "8000:8000"
    image: lab2-awf6che5hvf5ayh7.azurecr.io/backend:v1
  frontend:
    container_name: frontend
    platform: linux/amd64
    build:
      context: .
      dockerfile: dockerfiles/frontend.dockerfile
    ports: #mappar hosts till container streamlit 8501
      - "8501:8501"
    environment:
      BACKEND_URL: http://backend:8000 # Set the backend URL to point to the backend service within the Docker network
    image: lab2-awf6che5hvf5ayh7.azurecr.io/frontend:v1